import { NextResponse } from 'next/server'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'
export const revalidate = 0

// Masks a value to avoid leaking secrets
function mask(val?: string | null) {
  if (!val) return 'undefined'
  if (val.length <= 8) return '****'
  return `${val.slice(0, 6)}…${val.slice(-4)}`
}

export async function GET() {
  const keys = {
    // Core
    STRIPE_SECRET_KEY: !!process.env.STRIPE_SECRET_KEY,

    // Canonical keys used by unified pricing/checkout
    STRIPE_PRICE_AI_BLUEPRINT_TEAM_MONTHLY: !!process.env.STRIPE_PRICE_AI_BLUEPRINT_TEAM_MONTHLY,
    STRIPE_PRICE_AI_BLUEPRINT_TEAM_YEARLY: !!process.env.STRIPE_PRICE_AI_BLUEPRINT_TEAM_YEARLY,
    STRIPE_PRICE_AI_BLUEPRINT_SELF_SERVE_ONETIME: !!process.env.STRIPE_PRICE_AI_BLUEPRINT_SELF_SERVE_ONETIME,
    STRIPE_PRICE_AI_BLUEPRINT_BOARD_READY_PRO_ONETIME: !!process.env.STRIPE_PRICE_AI_BLUEPRINT_BOARD_READY_PRO_ONETIME,
    STRIPE_PRICE_AI_BLUEPRINT_ENTERPRISE_PROGRAM_ONETIME: !!process.env.STRIPE_PRICE_AI_BLUEPRINT_ENTERPRISE_PROGRAM_ONETIME,

    // Legacy/alternates seen in repo/scripts
    STRIPE_PRICE_AI_READINESS_COMPLETE_MONTHLY: !!process.env.STRIPE_PRICE_AI_READINESS_COMPLETE_MONTHLY,
    STRIPE_PRICE_AI_READINESS_COMPLETE_YEARLY: !!process.env.STRIPE_PRICE_AI_READINESS_COMPLETE_YEARLY,
    STRIPE_PRICE_TEAM_SUBSCRIPTION_MONTHLY: !!process.env.STRIPE_PRICE_TEAM_SUBSCRIPTION_MONTHLY,
    STRIPE_PRICE_TEAM_SUBSCRIPTION_YEARLY: !!process.env.STRIPE_PRICE_TEAM_SUBSCRIPTION_YEARLY,
    STRIPE_PRICE_TEAM_MONTHLY: !!process.env.STRIPE_PRICE_TEAM_MONTHLY,
    STRIPE_PRICE_TEAM_YEARLY: !!process.env.STRIPE_PRICE_TEAM_YEARLY,
    STRIPE_PRICE_AI_BLUEPRINT_MEMBERSHIP_MONTHLY: !!process.env.STRIPE_PRICE_AI_BLUEPRINT_MEMBERSHIP_MONTHLY,
    STRIPE_PRICE_AI_BLUEPRINT_MEMBERSHIP_ANNUAL: !!process.env.STRIPE_PRICE_AI_BLUEPRINT_MEMBERSHIP_ANNUAL,
    STRIPE_PRICE_HIGHER_ED_PULSE_CHECK: !!process.env.STRIPE_PRICE_HIGHER_ED_PULSE_CHECK,
    STRIPE_PRICE_K12_PULSE_CHECK: !!process.env.STRIPE_PRICE_K12_PULSE_CHECK,
    STRIPE_PRICE_AI_BLUEPRINT_COMPREHENSIVE: !!process.env.STRIPE_PRICE_AI_BLUEPRINT_COMPREHENSIVE,
    STRIPE_PRICE_AI_TRANSFORMATION_BLUEPRINT: !!process.env.STRIPE_PRICE_AI_TRANSFORMATION_BLUEPRINT,
    STRIPE_PRICE_ENTERPRISE_PARTNERSHIP_MONTHLY: !!process.env.STRIPE_PRICE_ENTERPRISE_PARTNERSHIP_MONTHLY,
    STRIPE_PRICE_ENTERPRISE_PARTNERSHIP_ANNUAL: !!process.env.STRIPE_PRICE_ENTERPRISE_PARTNERSHIP_ANNUAL,
  }

  // For quick manual inspection of the actual values (masked)
  const sampleValues = {
    STRIPE_PRICE_AI_BLUEPRINT_TEAM_MONTHLY: mask(process.env.STRIPE_PRICE_AI_BLUEPRINT_TEAM_MONTHLY),
    STRIPE_PRICE_AI_BLUEPRINT_TEAM_YEARLY: mask(process.env.STRIPE_PRICE_AI_BLUEPRINT_TEAM_YEARLY),
    STRIPE_PRICE_AI_BLUEPRINT_SELF_SERVE_ONETIME: mask(process.env.STRIPE_PRICE_AI_BLUEPRINT_SELF_SERVE_ONETIME),
    STRIPE_PRICE_AI_BLUEPRINT_BOARD_READY_PRO_ONETIME: mask(process.env.STRIPE_PRICE_AI_BLUEPRINT_BOARD_READY_PRO_ONETIME),
    STRIPE_PRICE_AI_BLUEPRINT_ENTERPRISE_PROGRAM_ONETIME: mask(process.env.STRIPE_PRICE_AI_BLUEPRINT_ENTERPRISE_PROGRAM_ONETIME),
    STRIPE_PRICE_HIGHER_ED_PULSE_CHECK: mask(process.env.STRIPE_PRICE_HIGHER_ED_PULSE_CHECK),
    STRIPE_PRICE_AI_BLUEPRINT_COMPREHENSIVE: mask(process.env.STRIPE_PRICE_AI_BLUEPRINT_COMPREHENSIVE),
    STRIPE_PRICE_AI_TRANSFORMATION_BLUEPRINT: mask(process.env.STRIPE_PRICE_AI_TRANSFORMATION_BLUEPRINT),
    STRIPE_PRICE_AI_BLUEPRINT_MEMBERSHIP_MONTHLY: mask(process.env.STRIPE_PRICE_AI_BLUEPRINT_MEMBERSHIP_MONTHLY),
    STRIPE_PRICE_AI_BLUEPRINT_MEMBERSHIP_ANNUAL: mask(process.env.STRIPE_PRICE_AI_BLUEPRINT_MEMBERSHIP_ANNUAL),
  }

  return NextResponse.json({ keys, sampleValues })
}
