// AI Report Generator - Legacy compatibility
// This file provides backward compatibility for older imports
export * from './pdf-report-generator'
export { generatePDFReport as generateAIReadinessPDF } from './pdf-report-generator'
export { generatePDFReport as default } from './pdf-report-generator'

// Add missing AIReportGenerator class export
export class AIReportGenerator {
  async generateReport(options: any): Promise<Buffer> {
    // Simple implementation for now - should be enhanced for production
    const PDFDocument = require('pdfkit');
    const doc = new PDFDocument();
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    
    return new Promise((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      
      doc.fontSize(20).text('AI Readiness Assessment Report', { align: 'center' });
      doc.moveDown();
      doc.fontSize(12).text('Generated by AI Readiness Platform');
      
      doc.end();
    });
  }
}
