// AI Report Generator - Legacy compatibility
// This file provides backward compatibility for older imports
export * from './pdf-report-generator';
export { generatePDFReport as default, generatePDFReport as generateAIReadinessPDF } from './pdf-report-generator';

// Add missing AIReportGenerator class export
export class AIReportGenerator {
  async generateReport(options: any): Promise<Buffer> {
    // Simple implementation for now - should be enhanced for production
    const PDFDocument = require('pdfkit');
    const doc = new PDFDocument();
    const chunks: Uint8Array[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(new Uint8Array(chunk)));

    return new Promise((resolve) => {
      doc.on('end', () => {
        const combined = new Uint8Array(chunks.reduce((acc, chunk) => acc + chunk.length, 0));
        let offset = 0;
        for (const chunk of chunks) {
          combined.set(chunk, offset);
          offset += chunk.length;
        }
        resolve(Buffer.from(combined));
      });

      doc.fontSize(20).text('AI Readiness Assessment Report', { align: 'center' });
      doc.moveDown();
      doc.fontSize(12).text('Generated by AI Readiness Platform');

      doc.end();
    });
  }
}
