name: Password Token Cleanup

on:
  schedule:
    # Runs hourly at minute 5 (adjust schedule as required)
    - cron: '5 * * * *'
  workflow_dispatch: {}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke cleanup endpoint (header-auth)
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
        run: |
          BASE_URL="$APP_BASE_URL"
          if [ -z "$BASE_URL" ]; then
            echo "⚠️  APP_BASE_URL secret not configured in GitHub Secrets" >&2
            echo "📋 To configure: https://github.com/${{ github.repository }}/settings/secrets/actions" >&2
            echo "📖 See SECRETS_QUICKSTART.md for setup instructions" >&2
            exit 1
          fi
          if [ -z "$CRON_SECRET" ]; then
            echo "⚠️  CRON_SECRET GitHub secret not configured" >&2
            echo "📋 To configure: https://github.com/${{ github.repository }}/settings/secrets/actions" >&2
            echo "📖 See SECRETS_QUICKSTART.md for setup instructions" >&2
            exit 1
          fi
          echo "🧹 Calling cleanup endpoint at $BASE_URL/api/auth/password/setup/cleanup"
          http_code=$(curl -s -o response.json -w '%{http_code}' -X POST "$BASE_URL/api/auth/password/setup/cleanup" \
            -H "x-cron-secret: $CRON_SECRET" -H 'content-length: 0')
          echo "📊 Status: $http_code"
          echo "📄 Response:" && cat response.json
          if [ "$http_code" -ge 300 ]; then
            echo "❌ Request failed with status $http_code" >&2
            exit 1
          fi
          echo "✅ Cleanup request successful"

      - name: Validate response
        run: |
          if ! grep -q '"success":true' response.json; then
            echo '❌ Success flag not found in response' >&2
            cat response.json
            exit 1
          fi
          deleted=$(grep -E '"deleted":' response.json | sed -E 's/.*"deleted":[ ]*([0-9]+).*/\1/') || true
          if [ -z "$deleted" ]; then
            echo "ℹ️  No deleted field present (function may return void)" 
          else
            echo "✅ Deleted tokens: $deleted"
          fi
