name: Slack Community Automation

on:
  schedule:
    # Run every hour during business hours (9 AM - 5 PM EST)
    - cron: '0 14-22 * * 1-5'  # 9 AM - 5 PM EST = 2 PM - 10 PM UTC
    # Run at 2 PM EST every day for weekly content
    - cron: '0 19 * * *'       # 2 PM EST = 7 PM UTC
  
  workflow_dispatch:
    inputs:
      post_type:
        description: 'Type of post to send'
        required: true
        default: 'tip'
        type: choice
        options:
          - tip
          - discussion
          - blog
      category:
        description: 'Category (for discussions)'
        required: false
        default: 'general'
        type: choice
        options:
          - k12
          - higher_ed
          - general

jobs:
  slack-automation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Scheduled Slack Posts
        run: |
          curl -X GET \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            "${{ secrets.APP_BASE_URL }}/api/cron/slack"

  manual-post:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Send Manual Slack Post
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "action": "manual_post",
              "type": "${{ github.event.inputs.post_type }}",
              "category": "${{ github.event.inputs.category }}"
            }' \
            "${{ secrets.APP_BASE_URL }}/api/slack-automation"

  weekly-summary:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 19 * * 5'  # Friday at 2 PM EST
    
    steps:
      - name: Send Weekly Summary
        run: |
          # Send Friday policy discussion
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "action": "manual_post",
              "type": "discussion",
              "category": "general"
            }' \
            "${{ secrets.APP_BASE_URL }}/api/slack-automation"
